version: 0.4.{build}

branches:
  only:
  - master
  - /dev-.*/

configuration:
  - Release
# XXX: LNK1104: cannot open file 'python27_d.lib'
  # - Debug

clone_folder: c:\projects\triton

environment:
  # python is automatically found by the find_package's
  CAPSTONE_INCLUDE_DIRS: c:\projects\triton\build\capstone-3.0.4\include
  BOOST_ROOT: c:\Libraries\boost_1_59_0

  matrix:
    - platform: Win32
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\%configuration%\capstone.lib
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.4.1-x86-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.4.1-x86-win\bin\libz3.lib
      Z3_PKG: z3-4.4.1-x86-win.zip
      CMAKE_TEMPLATE: Visual Studio 14 2015
      PYTHON: "C:\\Python27"

    - platform: x64
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\x64\%configuration%\capstone.lib
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.4.1-x64-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.4.1-x64-win\bin\libz3.lib
      Z3_PKG: z3-4.4.1-x64-win.zip
      CMAKE_TEMPLATE: Visual Studio 14 2015 Win64
      PYTHON: "C:\\Python27-x64"

install:
  - set PATH=%PYTHON%;%PATH%
  - cmd: cd c:\projects\triton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo Downloading z3...
  - cmd: curl -fsSL -o %Z3_PKG% 'https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/%Z3_PKG%'
  - cmd: 7z x %Z3_PKG%
  - cmd: echo Downloading capstone...
  - cmd: curl -fsSL -o 3.0.4.zip 'https://github.com/aquynh/capstone/archive/3.0.4.zip'
  - cmd: 7z x 3.0.4.zip
  - cmd: echo Building capstone...
# This is required because capstone's slns/vcxprojs file have been made with an old version of MSVC which is not a problem in itself,
# the issue will show up when trying to link capstone.lib (generated with an old toolset) into triton that is generated with the new toolset.
# This result in annoying linking errors (sprintf/and similar functions don't get resolved) - we could also link legacy_stdio_definitions.lib to triton
# but I would rather build everything I can with the same toolset:
#   http://stackoverflow.com/questions/32418766/c-unresolved-external-symbol-sprintf-and-sscanf-in-visual-studio-2015
# The switch /p:PlatformToolset allows you to override the toolset version specified in the solution/project files :-)
  - cmd: msbuild capstone-3.0.4\msvc\capstone.sln /p:Configuration=%configuration% /p:Platform=%platform% /p:PlatformToolset=v140 /t:capstone_static /m
  - cmd: echo Running cmake...
  - cmd: cmake .. -G "%CMAKE_TEMPLATE%"

build:
  parallel: true
  project: c:\projects\triton\build\triton.sln

# This happens in the build directory: c:\projects\triton\build
before_test:
  - cmd: cmake --build . --config release --target install

test_script:
  - cmd: python.exe -m unittest discover ..\src\testers\unittests\

artifacts:
  - path: triton.*.7z
